'use strict';

/**
 * Pro subscription → feature CASCADE (DB-backed, pglite).
 *
 * Verifies handleWebhook's mapping and halt cascade end to end against a real Postgres
 * (pglite): a container sub funds its one service; the base sub funds the whole tier.
 *   - container halt        → only that container stops.
 *   - base HALT (transient) → all shared containers stop, Pro gate closes (plan→'max'),
 *                             every container sub is PAUSED (billing frozen).
 *   - base renewal          → gate reopens (plan→'pro'), paused subs RESUME + come online.
 *   - base CANCEL (final)   → teardown: all stopped, every container sub cancelled.
 *
 * The @rach/core pool is pointed at pglite; Razorpay subscription ops are spied (no net).
 */

// Env must be set before any @rach module resolves flags / Razorpay keys.
process.env.NODE_ENV = 'test';
process.env.FEATURE_PRO_TIER = 'true';
process.env.RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID || 'rzp_test_dummy';
process.env.RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET || 'dummy_secret';

const test = require('node:test');
const assert = require('node:assert/strict');

const HAVE_PGLITE = (() => { try { require.resolve('@electric-sql/pglite'); return true; } catch { return false; } })();

const core = require('@rach/core');
const billing = require('@rach/billing');
const P = require('../src/services/proSubscription');

let db;
const calls = { pause: [], resume: [], cancel: [], update: [], create: [], planCreate: [] };
const invoiceCalls = []; // spy on billing.issueInvoiceForPayment (renewal-cycle GST invoices)
const siteOps = { stop: [], resume: [], svcDelete: [] }; // spy on siteTeardown ops

test.before(async () => {
  const { PGlite } = await import('@electric-sql/pglite');
  db = new PGlite();
  await db.exec(`
    CREATE TABLE tenants  (id INT PRIMARY KEY, plan TEXT NOT NULL DEFAULT 'max', billing_currency VARCHAR(3), updated_at TIMESTAMPTZ DEFAULT NOW());
    CREATE TABLE projects (id INT PRIMARY KEY, tenant_id INT NOT NULL);
    CREATE TABLE services (
      id INT PRIMARY KEY, project_id INT NOT NULL, name TEXT,
      status TEXT NOT NULL DEFAULT 'draft', compute_target TEXT NOT NULL DEFAULT 'shared',
      compute_size TEXT NOT NULL DEFAULT 'nano', units INT NOT NULL DEFAULT 0,
      pending_order_id TEXT, pending_resize_order_id TEXT, pending_resize_size TEXT,
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE TABLE pro_subscriptions (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id INT NOT NULL, service_id INT,
      kind TEXT NOT NULL, razorpay_sub_id TEXT, razorpay_plan_id TEXT,
      amount_cents INT NOT NULL, currency VARCHAR(3) NOT NULL DEFAULT 'USD',
      compute_size TEXT NOT NULL DEFAULT 'nano', tier TEXT, status TEXT NOT NULL DEFAULT 'created',
      created_by INT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
    );
    CREATE UNIQUE INDEX uq_base ON pro_subscriptions(tenant_id) WHERE kind='base' AND status<>'cancelled';
    CREATE UNIQUE INDEX uq_svc  ON pro_subscriptions(service_id) WHERE service_id IS NOT NULL AND status<>'cancelled';
  `);

  // Point the shared pool at pglite (Service / plan / ProSub all use this same object).
  core.pool.query = (text, params) => (params === undefined ? db.query(text) : db.query(text, params));

  // Spy Razorpay subscription + plan ops (no network). `razorpay.subscriptions` is the cached
  // SDK resource object; patching it here is seen by every later proxy access.
  const subs = billing.razorpay.subscriptions;
  subs.pause  = async (id) => { calls.pause.push(id);  return {}; };
  subs.resume = async (id) => { calls.resume.push(id); return {}; };
  subs.cancel = async (id) => { calls.cancel.push(id); return {}; };
  subs.update = async (id, body) => { calls.update.push({ id, body }); return {}; };
  subs.create = async (body) => { calls.create.push(body); return { id: `sub_new_${calls.create.length}` }; };
  billing.razorpay.plans.create = async (body) => { calls.planCreate.push(body); return { id: `plan_new_${calls.planCreate.length}` }; };

  // Stub the tax gross-up (zero-tax): the pglite schema has no users/tax_registrations
  // tables, and these tests assert money orchestration, not GST math (pro_tax.test.js does).
  require('../src/services/proTax').grossUpFor = async ({ subtotalCents }) => (
    { subtotalCents, taxCents: 0, grossCents: subtotalCents }
  );

  // Spy the invoice engine — proSubscription resolves it as billing.issueInvoiceForPayment
  // at call time, so patching the module object here is seen by every webhook handled below.
  billing.issueInvoiceForPayment = async (payload) => {
    invoiceCalls.push(payload);
    return { ok: true, invoice: { total_minor: payload.lines[0].unit_price_minor } };
  };

  // Spy the site teardown/resume ops (same module-object patching) — the pglite schema has
  // no site columns, and what we assert here is that the RIGHT op is requested.
  const teardown = require('../src/services/siteTeardown');
  teardown.enqueueTenantStop = async (tid, reason) => { siteOps.stop.push({ tid, reason }); return true; };
  teardown.enqueueTenantResumeOp = async (tid, reason) => { siteOps.resume.push({ tid, reason }); return true; };
  teardown.enqueueServiceTeardown = async (tid, sid) => { siteOps.svcDelete.push({ tid, sid }); return true; };
});

async function reset() {
  await db.exec('TRUNCATE tenants, projects, services, pro_subscriptions;');
  await db.exec(`
    INSERT INTO tenants(id,plan) VALUES (1,'pro');
    INSERT INTO projects(id,tenant_id) VALUES (1,1);
    INSERT INTO services(id,project_id,name,status,compute_target,compute_size,units) VALUES
      (1,1,'app','online','shared','nano',1),
      (2,1,'db','online','shared','micro',1);
    INSERT INTO pro_subscriptions(id,tenant_id,service_id,kind,razorpay_sub_id,razorpay_plan_id,amount_cents,currency,compute_size,tier,status,created_by) VALUES
      (1,1,1,'base','sub_base','plan_base',3000,'USD','nano','pro','active',7),
      (2,1,2,'container','sub_c2','plan_c2',2000,'USD','micro',NULL,'active',7);
    ALTER TABLE pro_subscriptions ALTER COLUMN id RESTART WITH 100;
  `);
  for (const k of Object.keys(calls)) calls[k].length = 0;
  invoiceCalls.length = 0;
  siteOps.stop.length = 0; siteOps.resume.length = 0; siteOps.svcDelete.length = 0;
}

const svc  = async (id) => (await db.query('SELECT status FROM services WHERE id=$1', [id])).rows[0].status;
const sub  = async (rz) => (await db.query('SELECT status FROM pro_subscriptions WHERE razorpay_sub_id=$1', [rz])).rows[0].status;
const plan = async ()   => (await db.query('SELECT plan FROM tenants WHERE id=1')).rows[0].plan;

test('container sub halt stops only that container; the tier is untouched', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_c2', event: 'halted' });
  assert.equal(await svc(2), 'stopped');   // its feature halted
  assert.equal(await svc(1), 'online');    // sibling untouched
  assert.equal(await sub('sub_c2'), 'halted');
  assert.equal(await plan(), 'pro');       // gate stays open
});

test('base HALT freezes everything: gate closes, all stopped, container subs paused', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'halted' });
  assert.equal(await plan(), 'max');            // Pro gate closed
  assert.equal(await sub('sub_base'), 'halted');
  assert.equal(await sub('sub_c2'), 'paused');  // billing frozen, not cancelled
  assert.equal(await svc(1), 'stopped');
  assert.equal(await svc(2), 'stopped');
  assert.ok(calls.pause.includes('sub_c2'));    // paused in Razorpay
});

test('base renewal after halt resumes everything and reopens the gate', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'halted' });
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'charged' });
  assert.equal(await plan(), 'pro');
  assert.equal(await sub('sub_base'), 'active');
  assert.equal(await sub('sub_c2'), 'active');
  assert.equal(await svc(1), 'online');
  assert.equal(await svc(2), 'online');
  assert.ok(calls.resume.includes('sub_c2'));   // resumed in Razorpay
});

test('base CANCEL tears the tier down: all stopped, container subs cancelled', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'cancelled' });
  assert.equal(await plan(), 'max');
  assert.equal(await sub('sub_base'), 'cancelled');
  assert.equal(await sub('sub_c2'), 'cancelled');
  assert.equal(await svc(1), 'stopped');
  assert.equal(await svc(2), 'stopped');
  assert.ok(calls.cancel.includes('sub_c2'));
});

// ── Renewal-cycle invoicing + stale-webhook guard (re-audit 6 Sep, N2/N5) ─────────

test('renewal charge issues the GST invoice for the cycle: ex-GST line, keyed on the payment id', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_c2', event: 'charged', paymentId: 'pay_cycle2', amountMinor: 2000, currency: 'USD' });
  assert.equal(invoiceCalls.length, 1);
  const inv = invoiceCalls[0];
  assert.equal(inv.userId, 7);
  assert.equal(inv.currency, 'USD');
  assert.deepEqual(inv.lines, [{ description: 'RachBase container — micro (monthly)', quantity: 1, unit_price_minor: 2000 }]);
  assert.deepEqual(inv.payment, { razorpay_subscription_id: 'sub_c2', razorpay_payment_id: 'pay_cycle2' });
  assert.equal(await svc(2), 'online'); // and the container stays funded
});

test('base renewal invoice carries the tier label and the base ex-GST amount', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'charged', paymentId: 'pay_base2', amountMinor: 3000, currency: 'USD' });
  assert.equal(invoiceCalls.length, 1);
  assert.match(invoiceCalls[0].lines[0].description, /monthly base/);
  assert.equal(invoiceCalls[0].lines[0].unit_price_minor, 3000);
});

test('a charged event without a payment id (internal resume path) issues no invoice', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'halted' });
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'charged' }); // recovery without payment ctx
  assert.equal(invoiceCalls.length, 0);
});

test('a LATE charged on a cancelled sub never resurrects it — but the paid cycle is still invoiced', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'cancelled' });      // tier torn down
  invoiceCalls.length = 0;
  const out = await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'charged', paymentId: 'pay_late', amountMinor: 3000, currency: 'USD' });
  assert.equal(out.stale, true);
  assert.equal(await plan(), 'max');                 // gate stays closed
  assert.equal(await sub('sub_base'), 'cancelled');  // no resurrection
  assert.equal(await sub('sub_c2'), 'cancelled');
  assert.equal(await svc(1), 'stopped');             // nothing marked online
  assert.equal(await svc(2), 'stopped');
  assert.equal(invoiceCalls.length, 1);              // money moved → paper it
  assert.equal(invoiceCalls[0].payment.razorpay_payment_id, 'pay_late');
});

test('a replayed terminal event on a cancelled sub is a stale no-op (no duplicate teardown)', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'cancelled' });
  calls.cancel.length = 0;
  const out = await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'cancelled' });
  assert.equal(out.stale, true);
  assert.equal(calls.cancel.length, 0); // no second round of Razorpay cancels
});

// ── Halt must actually stop workloads ON THE SITE, reversibly (re-audit 6 Sep, N6) ────────

test('base HALT enqueues a reversible tenant suspend on the site (not just DB status flips)', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'halted' });
  assert.equal(siteOps.stop.length, 1);
  assert.equal(siteOps.stop[0].tid, 1);
  assert.equal(siteOps.stop[0].reason, 'payment_halted');
  assert.equal(siteOps.resume.length, 0);
});

test('EVERY paid base charge enqueues the site resume — halt recovery, routine renewal alike (audit #3 F1)', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  // A routine renewal ALSO enqueues the (idempotent, site-side no-op) resume: deriving it
  // from wasHalted missed unsubscribe→re-subscribe, replaced halted rows, and the
  // crash-after-setStatus retry — leaving paying customers at 0 replicas forever.
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'charged', paymentId: 'pay_r1', amountMinor: 3000, currency: 'USD' });
  assert.equal(siteOps.resume.length, 1);
  // Halt, then the retried charge lands → resume again, workloads back.
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'halted' });
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'charged', paymentId: 'pay_r2', amountMinor: 3000, currency: 'USD' });
  assert.equal(siteOps.resume.length, 2);
  assert.equal(siteOps.resume[1].tid, 1);
  assert.equal(await plan(), 'pro'); // gate reopened alongside the site resume
});

test('a webhook-activated base LOCKS the tenant billing currency (audit #3 F6)', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  assert.equal((await db.query('SELECT billing_currency FROM tenants WHERE id=1')).rows[0].billing_currency, null);
  await P.handleWebhook({ razorpaySubId: 'sub_base', event: 'charged', paymentId: 'pay_lock', amountMinor: 3000, currency: 'USD' });
  assert.equal((await db.query('SELECT billing_currency FROM tenants WHERE id=1')).rows[0].billing_currency, 'USD');
});

test('a HALTED base is cancelled and re-minted on same-tier re-subscribe, not resumed as a dead checkout (audit #3 F7)', { skip: !HAVE_PGLITE }, async () => {
  await db.exec('TRUNCATE tenants, projects, services, pro_subscriptions;');
  await db.exec(`
    INSERT INTO tenants(id,plan) VALUES (1,'max');
    INSERT INTO pro_subscriptions(id,tenant_id,service_id,kind,razorpay_sub_id,razorpay_plan_id,amount_cents,currency,compute_size,tier,status,created_by)
    VALUES (1,1,NULL,'base','sub_halted','plan_halted',3000,'USD','nano','pro','halted',7);
    ALTER TABLE pro_subscriptions ALTER COLUMN id RESTART WITH 100;
  `);
  for (const k of Object.keys(calls)) calls[k].length = 0;
  const out = await P.beginProBase({ tenantId: 1, tier: 'pro', currency: 'USD', userId: 7 });
  assert.ok(calls.cancel.includes('sub_halted'));    // dead sub cancelled (ends Razorpay dunning, by design)
  assert.equal(out.resumed, undefined);              // NOT handed back as a resumable checkout
  assert.equal(calls.create.length, 1);              // fresh subscription minted instead
  assert.equal(out.tier, 'pro');
  assert.equal((await db.query(`SELECT status FROM pro_subscriptions WHERE id=1`)).rows[0].status, 'cancelled');
});

test('upgrade promotion skips abandoned checkouts and already-waived rows (audit #3 F5)', { skip: !HAVE_PGLITE }, async () => {
  await db.exec('TRUNCATE tenants, projects, services, pro_subscriptions;');
  await db.exec(`
    INSERT INTO tenants(id,plan) VALUES (1,'starter');
    INSERT INTO projects(id,tenant_id) VALUES (1,1);
    INSERT INTO services(id,project_id,name,status,compute_target,compute_size,units) VALUES
      (1,1,'app','online','shared','nano',1),
      (2,1,'ghost','pending_payment','shared','nano',1),
      (3,1,'waived','online','shared','micro',1),
      (4,1,'paying','online','shared','micro',1);
    INSERT INTO pro_subscriptions(id,tenant_id,service_id,kind,razorpay_sub_id,razorpay_plan_id,amount_cents,currency,compute_size,tier,status,created_by) VALUES
      (1,1,NULL,'base','sub_base','plan_base',1000,'USD','nano','starter','active',7),
      (2,1,2,'container','sub_ghost','plan_g',1000,'USD','nano',NULL,'created',7),
      (3,1,3,'container','sub_waived','plan_w',1000,'USD','micro',NULL,'active',7),
      (4,1,4,'container','sub_paying','plan_p',2000,'USD','micro',NULL,'active',7);
    ALTER TABLE pro_subscriptions ALTER COLUMN id RESTART WITH 100;
  `);
  // Row 2 = abandoned checkout (oldest); row 3 = compute-only micro (fee already waived —
  // billable micro would be 2000); row 4 = the genuinely fee-paying container.
  for (const k of Object.keys(calls)) calls[k].length = 0;
  const out = await P.beginProBase({ tenantId: 1, tier: 'pro', currency: 'USD', userId: 7 });
  assert.equal(out.upgraded, true);
  assert.equal(out.promotedContainers, 1);           // ONLY the fee-paying row qualifies
  // The paying micro container is repriced to compute-only ($10) on its own mandate…
  const paying = (await db.query(`SELECT * FROM pro_subscriptions WHERE id=4`)).rows[0];
  assert.equal(paying.amount_cents, 1000);
  assert.ok(calls.update.some((u) => u.id === 'sub_paying'));
  // …while the abandoned checkout and the already-waived row are untouched.
  assert.equal((await db.query(`SELECT status FROM pro_subscriptions WHERE id=2`)).rows[0].status, 'created');
  assert.equal((await db.query(`SELECT amount_cents FROM pro_subscriptions WHERE id=3`)).rows[0].amount_cents, 1000);
  assert.ok(!calls.cancel.includes('sub_ghost'));
  assert.ok(!calls.update.some((u) => u.id === 'sub_waived'));
});

// ── Tier upgrade in place (audit H4: the Starter→Pro no-op) + currency lock (M1) ─────────

const containerBilling = require('../src/services/containerBilling');

// Starter tenant: base $10, container A free (no sub), containers B (micro, $20 sub) and
// C (nano, $10 sub) billable. Upgrading to Pro (3 included) must reprice the base and
// promote B → compute-only ($10) and C → free (sub cancelled).
async function seedStarterWithBillables() {
  await db.exec('TRUNCATE tenants, projects, services, pro_subscriptions;');
  await db.exec(`
    INSERT INTO tenants(id,plan) VALUES (1,'starter');
    INSERT INTO projects(id,tenant_id) VALUES (1,1);
    INSERT INTO services(id,project_id,name,status,compute_target,compute_size,units) VALUES
      (1,1,'app','online','shared','nano',1),
      (2,1,'db','online','shared','micro',1),
      (3,1,'cache','online','shared','nano',1);
    INSERT INTO pro_subscriptions(id,tenant_id,service_id,kind,razorpay_sub_id,razorpay_plan_id,amount_cents,currency,compute_size,tier,status,created_by) VALUES
      (1,1,NULL,'base','sub_base','plan_base',1000,'USD','nano','starter','active',7),
      (2,1,2,'container','sub_c2','plan_c2',2000,'USD','micro',NULL,'active',7),
      (3,1,3,'container','sub_c3','plan_c3',1000,'USD','nano',NULL,'active',7);
    ALTER TABLE pro_subscriptions ALTER COLUMN id RESTART WITH 100;
  `);
  for (const k of Object.keys(calls)) calls[k].length = 0;
}

test('upgrade starter→pro: base repriced, tier recorded, billables promoted into the new allowance', { skip: !HAVE_PGLITE }, async () => {
  await seedStarterWithBillables();
  const out = await P.beginProBase({ tenantId: 1, tier: 'pro', currency: 'USD', userId: 7 });
  assert.equal(out.upgraded, true);
  assert.equal(out.tier, 'pro');
  assert.equal(out.subtotalCents, 3000);        // pro base (USD, ex-GST)
  assert.equal(out.promotedContainers, 2);      // both billables moved into the +2 slots

  const base = (await db.query(`SELECT * FROM pro_subscriptions WHERE kind='base'`)).rows[0];
  assert.equal(base.tier, 'pro');
  assert.equal(base.amount_cents, 3000);
  assert.equal(base.razorpay_sub_id, 'sub_base'); // mandate reused — same subscription
  assert.equal(await plan(), 'pro');

  // Oldest billable (micro) → fee waived, compute-only $10 recurring on the SAME mandate.
  const c2 = (await db.query(`SELECT * FROM pro_subscriptions WHERE id=2`)).rows[0];
  assert.equal(c2.status, 'active');
  assert.equal(c2.amount_cents, 1000);
  assert.ok(calls.update.some((u) => u.id === 'sub_c2'));
  // Next billable (nano) → wholly free: its subscription is cancelled outright.
  const c3 = (await db.query(`SELECT * FROM pro_subscriptions WHERE id=3`)).rows[0];
  assert.equal(c3.status, 'cancelled');
  assert.ok(calls.cancel.includes('sub_c3'));
  // The base itself was repriced via subscriptions.update too (no new checkout).
  assert.ok(calls.update.some((u) => u.id === 'sub_base'));
  assert.equal(calls.create.length, 0); // and NO new subscription was created
});

test('downgrade pro→starter is refused (allowance would shrink under running containers)', { skip: !HAVE_PGLITE }, async () => {
  await reset(); // pro base active
  const out = await P.beginProBase({ tenantId: 1, tier: 'starter', currency: 'USD', userId: 7 });
  assert.equal(out.downgradeUnsupported, true);
  assert.equal(out.tier, 'pro');
  assert.equal((await db.query(`SELECT tier FROM pro_subscriptions WHERE kind='base'`)).rows[0].tier, 'pro'); // untouched
});

test('same-tier subscribe on an active base stays a no-op { alreadyActive }', { skip: !HAVE_PGLITE }, async () => {
  await reset();
  const out = await P.beginProBase({ tenantId: 1, tier: 'pro', currency: 'USD', userId: 7 });
  assert.equal(out.alreadyActive, true);
  assert.equal(calls.update.length, 0);
});

test('a stale UNPAID checkout at a different tier is cancelled and replaced, not resumed (audit M2)', { skip: !HAVE_PGLITE }, async () => {
  await db.exec('TRUNCATE tenants, projects, services, pro_subscriptions;');
  await db.exec(`
    INSERT INTO tenants(id,plan) VALUES (1,'max');
    INSERT INTO pro_subscriptions(id,tenant_id,service_id,kind,razorpay_sub_id,razorpay_plan_id,amount_cents,currency,compute_size,tier,status,created_by)
    VALUES (1,1,NULL,'base','sub_stale','plan_stale',1000,'USD','nano','starter','created',7);
    ALTER TABLE pro_subscriptions ALTER COLUMN id RESTART WITH 100;
  `);
  for (const k of Object.keys(calls)) calls[k].length = 0;
  const out = await P.beginProBase({ tenantId: 1, tier: 'pro', currency: 'USD', userId: 7 });
  assert.ok(calls.cancel.includes('sub_stale'));           // stale starter checkout dropped
  assert.equal(out.tier, 'pro');
  assert.equal(out.subtotalCents, 3000);                   // fresh PRO subscription created
  assert.equal(calls.create.length, 1);
  assert.equal((await db.query(`SELECT status FROM pro_subscriptions WHERE id=1`)).rows[0].status, 'cancelled');
});

test('billing currency locks at first activation and survives address-flavored re-resolution', { skip: !HAVE_PGLITE }, async () => {
  await db.exec('TRUNCATE tenants, projects, services, pro_subscriptions;');
  await db.exec(`INSERT INTO tenants(id,plan) VALUES (1,'max');
    CREATE TABLE IF NOT EXISTS users (id INT PRIMARY KEY, tenant_id INT, gstin TEXT, billing_address JSONB);`);
  // No lock yet + no India signal → USD.
  assert.equal(await containerBilling.billingCurrencyFor(1), 'USD');
  // Lock INR (as verifyProSubscription does from the paid base row) → INR wins from then on,
  // even though the users table would still say "not India".
  await containerBilling.lockBillingCurrency(1, 'INR');
  assert.equal(await containerBilling.billingCurrencyFor(1), 'INR');
  // Idempotent + never overwrites: a later USD lock attempt is a no-op.
  await containerBilling.lockBillingCurrency(1, 'USD');
  assert.equal(await containerBilling.billingCurrencyFor(1), 'INR');
});
