import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  Bell,
  BookOpen,
  Boxes,
  Brain,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Check,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  DoorOpen,
  Eye,
  FileCheck2,
  FileText,
  FlaskConical,
  Gauge,
  HeartPulse,
  Languages,
  Layers3,
  ListChecks,
  Lock,
  type LucideIcon,
  MessageSquare,
  Mic,
  Microscope,
  Network,
  PenLine,
  Phone,
  Pill,
  Plug,
  ReceiptText,
  ScanLine,
  ScrollText,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Sparkles,
  Stethoscope,
  TriangleAlert,
  UserCheck,
  Users,
  Webhook,
  Workflow,
  Zap,
  // --- extended set for additional verticals ---
  AlarmClock,
  Apple,
  Award,
  Banknote,
  BarChart3,
  BedDouble,
  Briefcase,
  Bug,
  Calculator,
  Car,
  ChefHat,
  Clock,
  CreditCard,
  Database,
  Dumbbell,
  FileSignature,
  Fingerprint,
  FolderOpen,
  Gavel,
  Gift,
  GraduationCap,
  HandCoins,
  Handshake,
  Headset,
  HeartHandshake,
  Home,
  Hotel,
  KeyRound,
  Landmark,
  Leaf,
  LifeBuoy,
  Mail,
  MapPin,
  Megaphone,
  Package,
  Percent,
  PieChart,
  PiggyBank,
  Route,
  Scale,
  ScanFace,
  School,
  Search,
  Send,
  ShoppingCart,
  Star,
  Tag,
  Target,
  Ticket,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  UserPlus,
  UserSearch,
  UtensilsCrossed,
  Wine,
  Wrench,
} from "lucide-react";

/**
 * Central icon map for the industry-demo system.
 *
 * Configs reference icons by `IconKey` (a plain string, so the config stays
 * serializable across the server→client boundary); components resolve the
 * actual component via `ICONS[key]`.
 */
export const ICONS = {
  // agents / roles
  intake: ClipboardList,
  triage: Activity,
  scribe: PenLine,
  coord: CalendarCheck,
  revenue: ReceiptText,
  knowledge: BookOpen,
  monitor: Siren,
  orchestrator: Workflow,

  // journey stages
  door: DoorOpen,
  diagnostics: FlaskConical,
  decision: UserCheck,
  follow: CalendarClock,

  // domains / misc
  shield: ShieldCheck,
  shieldAlert: ShieldAlert,
  alert: TriangleAlert,
  alert2: AlertTriangle,
  check: Check,
  network: Network,
  plug: Plug,
  webhook: Webhook,
  layers: Layers3,
  mic: Mic,
  arrowRight: ArrowRight,
  stethoscope: Stethoscope,
  scroll: ScrollText,
  users: Users,
  heart: HeartPulse,
  building: Building2,
  languages: Languages,
  phone: Phone,
  message: MessageSquare,
  calendar: CalendarDays,
  file: FileText,
  fileCheck: FileCheck2,
  dollar: CircleDollarSign,
  receipt: ReceiptText,
  clipboardCheck: ClipboardCheck,
  brain: Brain,
  lock: Lock,
  eye: Eye,
  bell: Bell,
  zap: Zap,
  gauge: Gauge,
  sparkles: Sparkles,
  pill: Pill,
  microscope: Microscope,
  badge: BadgeCheck,
  boxes: Boxes,
  listChecks: ListChecks,
  scan: ScanLine,

  // --- extended set for additional verticals ---
  home: Home,
  key: KeyRound,
  scale: Scale,
  gavel: Gavel,
  banknote: Banknote,
  landmark: Landmark,
  trendingUp: TrendingUp,
  chart: BarChart3,
  pieChart: PieChart,
  graduation: GraduationCap,
  school: School,
  hotel: Hotel,
  bed: BedDouble,
  utensils: UtensilsCrossed,
  chef: ChefHat,
  wine: Wine,
  car: Car,
  wrench: Wrench,
  truck: Truck,
  dumbbell: Dumbbell,
  apple: Apple,
  leaf: Leaf,
  gift: Gift,
  handshake: Handshake,
  heartHandshake: HeartHandshake,
  megaphone: Megaphone,
  briefcase: Briefcase,
  userPlus: UserPlus,
  userSearch: UserSearch,
  shoppingCart: ShoppingCart,
  package: Package,
  creditCard: CreditCard,
  banknotes: Banknote,
  calculator: Calculator,
  percent: Percent,
  handCoins: HandCoins,
  piggyBank: PiggyBank,
  tag: Tag,
  star: Star,
  trophy: Trophy,
  award: Award,
  target: Target,
  mapPin: MapPin,
  route: Route,
  search: Search,
  mail: Mail,
  send: Send,
  alarm: AlarmClock,
  clock: Clock,
  timer: Timer,
  ticket: Ticket,
  fileSignature: FileSignature,
  folder: FolderOpen,
  database: Database,
  bug: Bug,
  lifeBuoy: LifeBuoy,
  headset: Headset,
  scanFace: ScanFace,
  fingerprint: Fingerprint,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICONS;
